sudo: required
language: python
python:
  - 3.5.2
env:
  global:
    - DBPORT=9999
    - DOCKER_EMAIL=stop2@protonmail.com
    - DOCKER_USERNAME=stop2
    - secure: "giQ+UxU/+MeZ2caDmMA73ylUjsPIaJIiWR3ltX6T3AfZAVCzXJXoAOvcuk8SwfR8dmTVzTQsPexrUR9kGj49ZXn4t+BuvQ0VgPnNissLwjR3AqhEn3urq294apyW351AYWJxlTdW9UHc9q+y0E9NBrJ/Mmfh/Wo8TneYbMlb7xqVTLRdtjgzaCwmFPmLhcfLE9woRWvboIj8CAxA12GPoKGb5Fh3uHW7f1amZTMJTEUEAI0DLUXbLamiXEs7YFkxk87qAWJYka75YB9S9IFzwmDiol67UQOG/6mfFqdpWJA7IgNyy6KIdwJsmtAySKm1SoORrAFrWs6b12PxnHmWCKoK3meGQj1nxr9SQRDnduvt5j8Fs69Qb0wiwrPEyp1EygKOQQZJwM2MXtkrk4YGh+f4Z703Nc+T7vdSqMGLnRmkXTTUI/LDYY+SeXIua0q64AR+1WP5qjD4Pduv5zLoy7edmuDnKPtQ7ZjWGnP2SUo20xPZ7huuZdVdlylE3Q2QShnlXMoZg0t69wgEkXoDTTSJnnySp1xefotFiiCHAtxJmaCxx0uPVbwYyeLDpEbPnK7F3ZVExzHxPy2XR/IOaj/JfYkwAGOBxdTexe10/Q40qOFT5suMLESaUXeYuFXV6MVJZnCYBEAtcZ6TB6SKqu0TYRmdWP+FYFMRtdpuV30="
    - secure: "HdEmTsn5vsmHATt5nYm/qWyNjNbT1k8VwNUYYRovWVVZT0dYTLfwn6oLVfbGDxJHJitqUhc8+hyJN6abQYqUVJU/A4ATNEkfTs3ymfvR+2wKJ9L4e3vtjbyxHnE7RnhDD6uvFQHzhfPo1FX5LmZJn3IsRRveG4fehRWrPIYvX28GIXKF/7XDETY4pNX4NOH29+WqSFgA/tRGxMQVOU3d68+VFfmEsvWTes6efo2UXxhX+i2hVBx6GGkbvd5qm/HEKdy/DSSyChqqc1wIEeKHuTzaiEX9LzBNT4s17jo2fJ/9UjPNnCcEfFykk1OYFaak05wwp/7LhbKYkOuAgA7MXmrb+FEw3np7Nx3mCZ5YFJjt3CkmYneqAQx4cNw2R9qGCXUjRWMn2LQr8zSDmdBU/IB6zPW9HOVOltkU2HaTTqn3XR12OIBnm4Co9ywujBpUc6hYjATg3W9bYxB7Mcb6menhxG/Uko18mD10H7Cs7P2aDR3GN3VcKdc4seGQ6PGQWRUvaopj9MxC2DR1RDTQaR9wNqBBTHBsCpduqqPBpP+miGth3jyDNYJNMcmQBw0+b+fFvPiGeKHannndF3pVqtmqZ3Oxj2qKxd/7QdDHtSawyN1Em+CKQnKrAzMZF40SFQO8VeHVOm4ww+jBlEqjoQZhp19GuEdR1n+pZTxRSBI="
    - secure: "yFRaepXvtYGFXMfK1aB8G0YiVG3b0J+wi9vRf7H1Oedmrywr80udjVUMHATf+tOgO3uQ0mCkf6qkjYh7/RZfwH9uWSXOvilv2Ftm/uezRxWrAhGwCvQCYV6w7hneCwrAamH817F8uhX+yHDUOEp5IDTIdIzugraymvB6q4bKfQAh/W5Uco0hvFcsZephNH3RpOaKU1NgVrQX0qTo3jf+VGDhlKZWJdxaR53mSRf+7a9ky2pGoNlTaRKT+gNmqvOm5/IK9ZP1ARw33biOtsZmD8E90A31syWw4CCBCj32FafAmieHiOc3OvDA0gjJRJ4VkKEkcPqftEq+uCRPH7ESPt7ijNChey2mhjKiXKt3U8C827K3akdjVhFi24zTQnIRajt7Bky05wfIsZ9wyRl9QXx7+D3Q2sao/sIVaDVwCfJUYbVeXpTqjvN89xcCzJ0GJFcKLEb1cSgDOpA1SIeHyr1aZSgHxxE54aL19A6OFXO8xHmBK9zHvVJ2bpkS974zTG0IaUokS2JSdsJumqFG3hV+nSF3R/z8Wg5OeUkz3x4ycgDMWSub8kgocXFWquQIKQJgYVRsvfEeW2Z/IMZ6U62ghwBDiMeXZvcfJwV5sWNQR+VqoOInWxwgHpU3vLjt7w0XliPjnQ/ydTcsrGyh08NhpCIoYqzbRFVqdVZd0bc="
    - secure: "yesCMUD2qwWhDbqdrzCE/sCP6KneNeGNy5tpcreJNlaZhaf7xM8Z4xreTlDkO16+Y9yGg68IwSc7OKxBEXvPK5E+glEN1OYbCK+IqXFCpp+Qmv8ajs5UtEWjo4vmDLoJFat991AEFmkYKZ2QA+xyho1nkrwlSejXwgXIrFRC0qxyAx+V54kTihRWlMUkEUOt9J7hBJ3D6UNRNJkyhf2aUOSv1+c7fdG9r0+O/ny2yeE5dt5TZk2JB0Yn/eVAtewZSAgl2E+oiB9y3Eu2py/gpWMmrqnf7s0Gu7L/4NdwlCdnyZlDBQ+D3//KztdjncdruYTq97s2PZ86Yt9gxE0QZyompmmkS7+XWr88JmiUMgOqHE4fVAiAciOF8ANY5LEiN4ZN86JAYNdir9wyESysDgvoB9RKTYFI2DQDxpBD4Llhe5m7dSaYUvIuQWOrcwUJhdJp69xLBVg9pLYdBHrKOFfQ2i7IWWwwYDqIRIudrbBN+LYoLK8C848vI4DizeYXOJfUiZ8dFz6tdaY48M5yGoPu9BUbjn14Pn/Cs9vBCKtHPFbxT7Grx1UIq55q5B0w7NmcX0dhR8sVo2woiPskN334BsmXhjqG2Sk3mIZj2U9xDjNe68FANqw+yoqxSEOwR9ed7En0R6iYYIxVbuJCSsoWgvWeiYEyleMPnjDCL10="
services:
  - docker
  - docker-compose
script:
  - make test
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t stoptwo/backend .;
    docker push stoptwo/backend;
    docker login -e="$HEROKU_EMAIL" -u="$HEROKU_EMAIL" -p="$HEROKU_PASSWORD" registry.heroku.com;
    docker tag stoptwo/backend registry.heroku.com/stop20/web;
    docker tag stoptwo/backend registry.heroku.com/stop20-dev/web;
    docker push registry.heroku.com/stop20/web;
    docker push registry.heroku.com/stop20-dev/web;
    fi
notifications:
  slack: stop2:L8tGNnWgadReoqGDrfv93XBj
